### ISSUE TITLE
Crash at second iteration of Each when one of the components contains reference-typed members

### ISSUE THREAD

**Issue by dtaralla** [BeanCheeseBurrito/Flecs.NET#39]
Hello,

As soon as I have 2 entities with a component containing a reference type, calling `Each` crashes at the second iteration. First iteration executes correctly though. Error varies according to what components each entity has, seems like some memory corruption issue or weird marshalling going on?

Sample code to reproduce:

```c#
record struct A(object c, int a);

world.Entity("e1")
    .Set(new A(null!, 0))

world.Entity("e2")
    .Set(new A(null!, 0))

world
    .Query<A>()
    .Each((Entity entity, ref A a) =>
    {
        System.Console.WriteLine(entity.ToString());
    });
```
This will write "e1" as expected, then crashes at the second iteration with:
```log
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Runtime.InteropServices.GCHandle.get_Target()
   at Flecs.NET.Core.Invoker.Each[T0](ecs_iter_t* iter, EachEntityRefCallback`1 callback)
   at Flecs.NET.Core.Query.Each[T0](EachEntityRefCallback`1 callback)
```

The underlying issue really seems related to the reference type. If I remove the `object c` member, both iterations run fine.
If I add a simple component B, the crash becomes even weirder:
```c#
record struct A(object c, int a);
record struct B(float b);

...

world.Entity("e1")
    .Set(new A(null!, 0))
    .Set(new B(2f));

world.Entity("e2")
    .Set(new A(null!, 0))
    .Set(new B(2f));

world
    .Query<A, B>()
    .Each((Entity entity, ref A a, ref B b) =>
    {
        System.Console.WriteLine(entity.ToString());
    });
```

Crash at second iteration:
```log
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
```

Is using references in components not supported by Flecs.NET? Must it only be value types? I couldn't find anything in the readme/examples/docs about it.

Thanks!

**Comment by BeanCheeseBurrito** [comment]
This is related to this isssue https://github.com/BeanCheeseBurrito/Flecs.NET/issues/35. The wrapper sets the incorrect size for managed structs. This will be fixed in the next NuGet release.
