### ISSUE TITLE
Docs update: rename `EcsOnUpdate` to `Ecs.OnUpdate`

### ISSUE THREAD

**Issue by miguno** [BeanCheeseBurrito/Flecs.NET#4]
The docs use outdated names for phases, e.g. at https://beancheeseburrito.github.io/Flecs.NET.Docs/docs/documentation/quickstart#system.

Wrong (current):

```csharp
moveRoutine.Entity.Add(EcsOnUpdate);
```

Should be:

```csharp
moveRoutine.Entity.Add(Ecs.OnUpdate);
```

Thanks for your work on these bindings!

**Comment by BeanCheeseBurrito** [comment]
Fixed in https://github.com/BeanCheeseBurrito/Flecs.NET.Docs/commit/52ed2989566474bbfb6009e4fb5a3cfa2e16ee7e. Let me know if there are anymore changes that should be made.

> Thanks for your work on these bindings!

No problem!
